"""
Base Agent Module
Provides common functionality for all specialized AI agents
"""

import os
import sys
import json
from datetime import datetime
from typing import Optional, Dict, Any, List

# Ensure parent directory is in path for imports
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from integrations.llm.llm_client_v2 import create_llm_client, LLMClient
from utils.file_manager import FileManager
from core.config_loader import ConfigLoader
from core.logger import Logger
from core.conversation_summarizer import ConversationSummarizer
from core.context_orchestrator import ContextOrchestrator

class BaseAgent:
    def __init__(
        self,
        name: str,
        config_path: str = "backend/config/config.ini",
        config_dict: Optional[Dict[str, Any]] = None,
    ):
        self.name = name
        self.logger = Logger(f"{name}Agent")

        if config_dict:
            self.config_dict = config_dict
            self.config_loader = None
        else:
            self.config_loader = ConfigLoader(config_path)
            self.config_dict = {
                "llm": self.config_loader.get_section("llm"),
                "data": self.config_loader.get_section("data"),
                "user": self.config_loader.get_section("user"),
                "system": self.config_loader.get_section("system"),
                "news": self.config_loader.get_section("news"),
                "outfit": self.config_loader.get_section("outfit"),
                "life": self.config_loader.get_section("life"),
                "review": self.config_loader.get_section("review"),
                "work": self.config_loader.get_section("work"),
            }

        self.llm: LLMClient = create_llm_client(config_path=config_path)
        self.file_manager = FileManager(self.config_dict.get("data", {}))
        
        self.summarizer = ConversationSummarizer(self.llm)
        self.orchestrator = ContextOrchestrator(self.llm)

    def _save_log(self, file_type: str, content: str, title: str) -> bool:
        timestamp = datetime.now().strftime("%Y年%m月%d日 %H:%M")
        final_content = f"# {title} - {timestamp}\n\n{content}\n\n---\n*Generated by AI Life Assistant v2.0*"

        success = self.file_manager.save_daily_file(file_type, final_content)
        if success:
            self.logger.info(f"Successfully saved {file_type} log.")
            # 1. Generate Summary
            self.summarizer.generate_and_save_summary(self.name, [{"role": "assistant", "content": content}])
            # 2. Extract and Store Long-term Insights
            self.orchestrator.memory_mgr.extract_and_store_insights(self.name, content)
        else:
            self.logger.error(f"Failed to save {file_type} log.")
        return success

    def run(self, **kwargs) -> str:
        raise NotImplementedError("Subclasses must implement run()")

    def execute(self, **kwargs) -> str:
        return self.run(**kwargs)
