"""Add agent memory model

Revision ID: 1f0fc9a8db18
Revises: af7af7cf65af
Create Date: 2026-02-04 21:22:19.068831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f0fc9a8db18"
down_revision: Union[str, Sequence[str], None] = "af7af7cf65af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_memories_agent_id"), "agent_memories", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_memories_id"), "agent_memories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_memories_key"), "agent_memories", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_agent_memories_user_id"), "agent_memories", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_memories_user_id"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_key"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_id"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_agent_id"), table_name="agent_memories")
    op.drop_table("agent_memories")
    # ### end Alembic commands ###
