"""Add expires_at to memory

Revision ID: 59504f772b41
Revises: 91d7611ac274
Create Date: 2026-02-04 22:12:46.951446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59504f772b41'
down_revision: Union[str, Sequence[str], None] = '91d7611ac274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memories', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_column('agent_memories', 'expires_at')
    # ### end Alembic commands ###
